INSERT INTO Author(author_name,book_id) VALUES ('Mike Coburn',1);
INSERT INTO Author(author_name,book_id) VALUES ('John Silvester',2);
INSERT INTO Author(author_name,book_id) VALUES ('Andrew Tate',2);
INSERT INTO Author(author_name,book_id) VALUES ('Julia Quinn',3);
INSERT INTO Author(author_name,book_id) VALUES ('Andrew Hunter Murray',4);
INSERT INTO Author(author_name,book_id) VALUES ('James Harkin',4);
INSERT INTO Author(author_name,book_id) VALUES ('John Lloyd',4);
INSERT INTO Author(author_name,book_id) VALUES ('John Mitchinson',4);
INSERT INTO Author(author_name,book_id) VALUES ('The Try Guys',5);
INSERT INTO Author(author_name,book_id) VALUES ('Stephen Hawking',6);
INSERT INTO Author(author_name,book_id) VALUES ('Leonard Mlodinow',6);
INSERT INTO Author(author_name,book_id) VALUES ('James Harkin',7);
INSERT INTO Author(author_name,book_id) VALUES ('John Lloyd',7);
INSERT INTO Author(author_name,book_id) VALUES ('John Mitchinson',7);
INSERT INTO Author(author_name,book_id) VALUES ('Richard Osman',8);
INSERT INTO Author(author_name,book_id) VALUES ('Alexander Armstrong',8);
INSERT INTO Author(author_name,book_id) VALUES ('Sam Harris',9);
INSERT INTO Author(author_name,book_id) VALUES ('Disney Book Group',10);
INSERT INTO Author(author_name,book_id) VALUES ('The Muffin Brothers',11);
INSERT INTO Author(author_name,book_id) VALUES ('Bruce Lipton',12);
INSERT INTO Author(author_name,book_id) VALUES ('Running Press',13);
INSERT INTO Author(author_name,book_id) VALUES ('Mark Evans',14);
INSERT INTO Author(author_name,book_id) VALUES ('Dr Allan Ropper',15);
INSERT INTO Author(author_name,book_id) VALUES ('Brian David Burrell',15);
INSERT INTO Author(author_name,book_id) VALUES ('John Lloyd',16);
INSERT INTO Author(author_name,book_id) VALUES ('John Mitchinson',16);
INSERT INTO Author(author_name,book_id) VALUES ('Griff Rhys-Jones',17);
INSERT INTO Author(author_name,book_id) VALUES ('Mary Roach',18);
INSERT INTO Author(author_name,book_id) VALUES ('Harry H. Corbett',19);
INSERT INTO Author(author_name,book_id) VALUES ('Alan Simpson',19);
INSERT INTO Author(author_name,book_id) VALUES ('Full Cast',19);
INSERT INTO Author(author_name,book_id) VALUES ('Ray Galton',19);
INSERT INTO Author(author_name,book_id) VALUES ('Wilfrid Brambell',19);
INSERT INTO Author(author_name,book_id) VALUES ('Daniel Bettridge',20);
INSERT INTO Author(author_name,book_id) VALUES ('Bryan Sykes',21);
INSERT INTO Author(author_name,book_id) VALUES ('Paul Whitehouse',22);
INSERT INTO Author(author_name,book_id) VALUES ('Bob Mortimer',22);
INSERT INTO Author(author_name,book_id) VALUES ('William Sutcliffe',23);
INSERT INTO Author(author_name,book_id) VALUES ('Klaus Schwab',24);
INSERT INTO Author(author_name,book_id) VALUES ('Big Narstie',25);
INSERT INTO Author(author_name,book_id) VALUES ('Harry Hill',26);
INSERT INTO Author(author_name,book_id) VALUES ('Steven Johnson',27);
INSERT INTO Author(author_name,book_id) VALUES ('Nicholas Lyndhurst',28);
INSERT INTO Author(author_name,book_id) VALUES ('Full Cast',28);
INSERT INTO Author(author_name,book_id) VALUES ('David Jason',28);
INSERT INTO Author(author_name,book_id) VALUES ('John Sullivan',28);
INSERT INTO Author(author_name,book_id) VALUES ('Big Narstie',29);
INSERT INTO Author(author_name,book_id) VALUES ('Michio Kaku',30);
INSERT INTO Author(author_name,book_id) VALUES ('Charlie Brooker',31);
INSERT INTO Author(author_name,book_id) VALUES ('Alan Partridge',32);
INSERT INTO Author(author_name,book_id) VALUES ('Thomas L. Friedman',33);
INSERT INTO Author(author_name,book_id) VALUES ('Trey Parker',34);
INSERT INTO Author(author_name,book_id) VALUES ('Matt Stone',34);
INSERT INTO Author(author_name,book_id) VALUES ('Paul Ruditis',35);
INSERT INTO Author(author_name,book_id) VALUES ('Richard Dawkins',36);
INSERT INTO Author(author_name,book_id) VALUES ('Running Press',37);
INSERT INTO Author(author_name,book_id) VALUES ('League Of Gentlemen',38);
INSERT INTO Author(author_name,book_id) VALUES ('Theodore Gray',39);
INSERT INTO Author(author_name,book_id) VALUES ('Paul Merton',40);
INSERT INTO Author(author_name,book_id) VALUES ('Nick Martin',40);
INSERT INTO Author(author_name,book_id) VALUES ('Ian Hislop',40);
INSERT INTO Author(author_name,book_id) VALUES ('Sue Perkin',41);
INSERT INTO Author(author_name,book_id) VALUES ('Louise Hay',42);
INSERT INTO Author(author_name,book_id) VALUES ('Harry Hill',43);
INSERT INTO Author(author_name,book_id) VALUES ('Harry Hill',44);
INSERT INTO Author(author_name,book_id) VALUES ('Erik Brynjolfsson',45);
INSERT INTO Author(author_name,book_id) VALUES ('Andrew McAfee',45);
INSERT INTO Author(author_name,book_id) VALUES ('Matt Groening',47);
INSERT INTO Author(author_name,book_id) VALUES ('William Bynum',48);
INSERT INTO Author(author_name,book_id) VALUES ('Jasper Carrott',49);
INSERT INTO Author(author_name,book_id) VALUES ('Celia Imrie',50);
INSERT INTO Author(author_name,book_id) VALUES ('Julie Walters',50);
INSERT INTO Author(author_name,book_id) VALUES ('Victoria Wood',50);
INSERT INTO Author(author_name,book_id) VALUES ('Steven Pinker',51);
INSERT INTO Author(author_name,book_id) VALUES ('Paul Eddington',52);
INSERT INTO Author(author_name,book_id) VALUES ('Nigel Hawthorne',52);
INSERT INTO Author(author_name,book_id) VALUES ('Mark Williams',53);
INSERT INTO Author(author_name,book_id) VALUES ('Paul Whitehouse',53);
INSERT INTO Author(author_name,book_id) VALUES ('Charlie Higson',53);
INSERT INTO Author(author_name,book_id) VALUES ('Daniel Levitin',54);
INSERT INTO Author(author_name,book_id) VALUES ('David Walliams',56);
INSERT INTO Author(author_name,book_id) VALUES ('Matt Lucas and David Walliams',56);
INSERT INTO Author(author_name,book_id) VALUES ('Matt Lucas',56);
INSERT INTO Author(author_name,book_id) VALUES ('Tom Baker',56);
INSERT INTO Author(author_name,book_id) VALUES ('Jacob Bronowski',57);
INSERT INTO Author(author_name,book_id) VALUES ('Melanie Mitchell',58);
INSERT INTO Author(author_name,book_id) VALUES ('Louis Theroux',60);
INSERT INTO Author(author_name,book_id) VALUES ('Martin Blaser',61);
INSERT INTO Author(author_name,book_id) VALUES ('John Cleese',62);
INSERT INTO Author(author_name,book_id) VALUES ('Connie Booth',62);
INSERT INTO Author(author_name,book_id) VALUES ('John Cleese',63);
INSERT INTO Author(author_name,book_id) VALUES ('Connie Booth',63);
INSERT INTO Author(author_name,book_id) VALUES ('John Cleese and Connie Booth',63);
INSERT INTO Author(author_name,book_id) VALUES ('Full Cast',63);
INSERT INTO Author(author_name,book_id) VALUES ('N. Katherine Hayles',64);
INSERT INTO Author(author_name,book_id) VALUES ('Reece Shearsmith',65);
INSERT INTO Author(author_name,book_id) VALUES ('Mark Gatiss',65);
INSERT INTO Author(author_name,book_id) VALUES ('Steve Pemberton',65);
INSERT INTO Author(author_name,book_id) VALUES ('Paul Zenon',66);
INSERT INTO Author(author_name,book_id) VALUES ('Alan Simpson',66);
INSERT INTO Author(author_name,book_id) VALUES ('Paul Burton',66);
INSERT INTO Author(author_name,book_id) VALUES ('Ray Galton',66);
INSERT INTO Author(author_name,book_id) VALUES ('Gina Rippon',67);
INSERT INTO Author(author_name,book_id) VALUES ('Steve N Allen',68);
INSERT INTO Author(author_name,book_id) VALUES ('Chris Hughes',69);
INSERT INTO Author(author_name,book_id) VALUES ('Sam Harris',70);
INSERT INTO Author(author_name,book_id) VALUES ('Count Arthur Strong',71);
INSERT INTO Author(author_name,book_id) VALUES ('Hugh Laurie',72);
INSERT INTO Author(author_name,book_id) VALUES ('Rowan Atkinson',72);
INSERT INTO Author(author_name,book_id) VALUES ('Ben Elton',72);
INSERT INTO Author(author_name,book_id) VALUES ('Rik Mayall',72);
INSERT INTO Author(author_name,book_id) VALUES ('Tim McInnery',72);
INSERT INTO Author(author_name,book_id) VALUES ('Miranda Richardson',72);
INSERT INTO Author(author_name,book_id) VALUES ('Full Cast',72);
INSERT INTO Author(author_name,book_id) VALUES ('Richard Curtis',72);
INSERT INTO Author(author_name,book_id) VALUES ('Tony Robinson',72);
INSERT INTO Author(author_name,book_id) VALUES ('Stephen Fry',72);
INSERT INTO Author(author_name,book_id) VALUES ('Daniel Chamovitz',73);
INSERT INTO Author(author_name,book_id) VALUES ('Ricky Gervais',74);
INSERT INTO Author(author_name,book_id) VALUES ('Joel Levy',76);
INSERT INTO Author(author_name,book_id) VALUES ('Jimmy Jones',77);
INSERT INTO Author(author_name,book_id) VALUES ('Paul Abbott',78);
INSERT INTO Author(author_name,book_id) VALUES ('Jamie Metzl',79);
INSERT INTO Author(author_name,book_id) VALUES ('Ray Galton',80);
INSERT INTO Author(author_name,book_id) VALUES ('Matt Lucas',81);
INSERT INTO Author(author_name,book_id) VALUES ('Tom Baker',81);
INSERT INTO Author(author_name,book_id) VALUES ('David Williams',81);
INSERT INTO Author(author_name,book_id) VALUES ('Dr. Catherine Dawson',82);
INSERT INTO Author(author_name,book_id) VALUES ('Cala Spinner',83);
INSERT INTO Author(author_name,book_id) VALUES ('George Mainwaring',84);
INSERT INTO Author(author_name,book_id) VALUES ('Hannah R. Rothstein',85);
INSERT INTO Author(author_name,book_id) VALUES ('Larry V. Hedges',85);
INSERT INTO Author(author_name,book_id) VALUES ('Julian P. T. Higgins',85);
INSERT INTO Author(author_name,book_id) VALUES ('Michael Borenstein',85);
INSERT INTO Author(author_name,book_id) VALUES ('Emma Marriott',87);
INSERT INTO Author(author_name,book_id) VALUES ('Natalie Jerome',87);
INSERT INTO Author(author_name,book_id) VALUES ('E. T. Jaynes',88);
INSERT INTO Author(author_name,book_id) VALUES ('G. Larry Bretthorst',88);
INSERT INTO Author(author_name,book_id) VALUES ('Celia Imrie',90);
INSERT INTO Author(author_name,book_id) VALUES ('Julie Walters',90);
INSERT INTO Author(author_name,book_id) VALUES ('Thelma Barlow',90);
INSERT INTO Author(author_name,book_id) VALUES ('Victoria Wood',90);
INSERT INTO Author(author_name,book_id) VALUES ('Yuk Hui',91);
INSERT INTO Author(author_name,book_id) VALUES ('Euclid',94);
INSERT INTO Author(author_name,book_id) VALUES ('Ernie Wise',95);
INSERT INTO Author(author_name,book_id) VALUES ('Eric Morecambe',95);
INSERT INTO Author(author_name,book_id) VALUES ('Jasper Carrott',96);
INSERT INTO Author(author_name,book_id) VALUES ('Sean B. Carroll',97);
INSERT INTO Author(author_name,book_id) VALUES ('Jon Sopel',98);
INSERT INTO Author(author_name,book_id) VALUES ('Tony Pritchard',99);
INSERT INTO Author(author_name,book_id) VALUES ('Paul Carpenter',99);
INSERT INTO Author(author_name,book_id) VALUES ('Tony Robinson',100);
