INSERT INTO Category(category_name,book_id) VALUES ('Fantasy',1);
INSERT INTO Category(category_name,book_id) VALUES ('Horror',1);
INSERT INTO Category(category_name,book_id) VALUES ('Science Fiction',1);
INSERT INTO Category(category_name,book_id) VALUES ('Classics',1);
INSERT INTO Category(category_name,book_id) VALUES ('Classics',2);
INSERT INTO Category(category_name,book_id) VALUES ('Comedy',2);
INSERT INTO Category(category_name,book_id) VALUES ('Self-help',2);
INSERT INTO Category(category_name,book_id) VALUES ('Dystopian',2);
INSERT INTO Category(category_name,book_id) VALUES ('Historical Fiction',3);
INSERT INTO Category(category_name,book_id) VALUES ('Mystery',3);
INSERT INTO Category(category_name,book_id) VALUES ('Self-help',3);
INSERT INTO Category(category_name,book_id) VALUES ('Thriller',3);
INSERT INTO Category(category_name,book_id) VALUES ('Science Fiction',3);
INSERT INTO Category(category_name,book_id) VALUES ('Romance',4);
INSERT INTO Category(category_name,book_id) VALUES ('Science Fiction',4);
INSERT INTO Category(category_name,book_id) VALUES ('Poetry',4);
INSERT INTO Category(category_name,book_id) VALUES ('Comedy',5);
INSERT INTO Category(category_name,book_id) VALUES ('Mystery',5);
INSERT INTO Category(category_name,book_id) VALUES ('Dystopian',6);
INSERT INTO Category(category_name,book_id) VALUES ('Adventure',6);
INSERT INTO Category(category_name,book_id) VALUES ('Children''s',6);
INSERT INTO Category(category_name,book_id) VALUES ('Horror',6);
INSERT INTO Category(category_name,book_id) VALUES ('Romance',7);
INSERT INTO Category(category_name,book_id) VALUES ('Mystery',8);
INSERT INTO Category(category_name,book_id) VALUES ('Short Stories',8);
INSERT INTO Category(category_name,book_id) VALUES ('Children''s',9);
INSERT INTO Category(category_name,book_id) VALUES ('Young Adult',9);
INSERT INTO Category(category_name,book_id) VALUES ('Travel',9);
INSERT INTO Category(category_name,book_id) VALUES ('Young Adult',10);
INSERT INTO Category(category_name,book_id) VALUES ('Fantasy',10);
INSERT INTO Category(category_name,book_id) VALUES ('Children''s',10);
INSERT INTO Category(category_name,book_id) VALUES ('Short Stories',10);
INSERT INTO Category(category_name,book_id) VALUES ('Science Fiction',11);
INSERT INTO Category(category_name,book_id) VALUES ('Poetry',12);
INSERT INTO Category(category_name,book_id) VALUES ('Horror',12);
INSERT INTO Category(category_name,book_id) VALUES ('Travel',12);
INSERT INTO Category(category_name,book_id) VALUES ('Biography',12);
INSERT INTO Category(category_name,book_id) VALUES ('Horror',13);
INSERT INTO Category(category_name,book_id) VALUES ('Philosophy',14);
INSERT INTO Category(category_name,book_id) VALUES ('Poetry',14);
INSERT INTO Category(category_name,book_id) VALUES ('Children''s',14);
INSERT INTO Category(category_name,book_id) VALUES ('Biography',14);
INSERT INTO Category(category_name,book_id) VALUES ('Poetry',15);
INSERT INTO Category(category_name,book_id) VALUES ('Dystopian',15);
INSERT INTO Category(category_name,book_id) VALUES ('Thriller',16);
INSERT INTO Category(category_name,book_id) VALUES ('Fantasy',17);
INSERT INTO Category(category_name,book_id) VALUES ('Classics',17);
INSERT INTO Category(category_name,book_id) VALUES ('Self-help',18);
INSERT INTO Category(category_name,book_id) VALUES ('Poetry',18);
INSERT INTO Category(category_name,book_id) VALUES ('Romance',18);
INSERT INTO Category(category_name,book_id) VALUES ('Horror',19);
INSERT INTO Category(category_name,book_id) VALUES ('Crime',20);
INSERT INTO Category(category_name,book_id) VALUES ('Comedy',20);
INSERT INTO Category(category_name,book_id) VALUES ('Short Stories',20);
INSERT INTO Category(category_name,book_id) VALUES ('Poetry',21);
INSERT INTO Category(category_name,book_id) VALUES ('Classics',21);
INSERT INTO Category(category_name,book_id) VALUES ('Romance',21);
INSERT INTO Category(category_name,book_id) VALUES ('Mystery',21);
INSERT INTO Category(category_name,book_id) VALUES ('Biography',22);
INSERT INTO Category(category_name,book_id) VALUES ('Historical Fiction',22);
INSERT INTO Category(category_name,book_id) VALUES ('Philosophy',22);
INSERT INTO Category(category_name,book_id) VALUES ('Dystopian',23);
INSERT INTO Category(category_name,book_id) VALUES ('Fantasy',23);
INSERT INTO Category(category_name,book_id) VALUES ('Horror',23);
INSERT INTO Category(category_name,book_id) VALUES ('Mystery',23);
INSERT INTO Category(category_name,book_id) VALUES ('Mystery',24);
INSERT INTO Category(category_name,book_id) VALUES ('Short Stories',24);
INSERT INTO Category(category_name,book_id) VALUES ('Fantasy',24);
INSERT INTO Category(category_name,book_id) VALUES ('Self-help',24);
INSERT INTO Category(category_name,book_id) VALUES ('Thriller',25);
INSERT INTO Category(category_name,book_id) VALUES ('Adventure',25);
INSERT INTO Category(category_name,book_id) VALUES ('Self-help',26);
INSERT INTO Category(category_name,book_id) VALUES ('Crime',26);
INSERT INTO Category(category_name,book_id) VALUES ('Poetry',26);
INSERT INTO Category(category_name,book_id) VALUES ('Short Stories',26);
INSERT INTO Category(category_name,book_id) VALUES ('Young Adult',26);
INSERT INTO Category(category_name,book_id) VALUES ('Children''s',27);
INSERT INTO Category(category_name,book_id) VALUES ('Adventure',28);
INSERT INTO Category(category_name,book_id) VALUES ('Poetry',28);
INSERT INTO Category(category_name,book_id) VALUES ('Thriller',28);
INSERT INTO Category(category_name,book_id) VALUES ('Horror',28);
INSERT INTO Category(category_name,book_id) VALUES ('Poetry',29);
INSERT INTO Category(category_name,book_id) VALUES ('Romance',29);
INSERT INTO Category(category_name,book_id) VALUES ('Short Stories',29);
INSERT INTO Category(category_name,book_id) VALUES ('Comedy',29);
INSERT INTO Category(category_name,book_id) VALUES ('Adventure',29);
INSERT INTO Category(category_name,book_id) VALUES ('Fantasy',30);
INSERT INTO Category(category_name,book_id) VALUES ('Travel',31);
INSERT INTO Category(category_name,book_id) VALUES ('Short Stories',31);
INSERT INTO Category(category_name,book_id) VALUES ('Romance',31);
INSERT INTO Category(category_name,book_id) VALUES ('Travel',32);
INSERT INTO Category(category_name,book_id) VALUES ('Young Adult',32);
INSERT INTO Category(category_name,book_id) VALUES ('Poetry',32);
INSERT INTO Category(category_name,book_id) VALUES ('Travel',33);
INSERT INTO Category(category_name,book_id) VALUES ('Comedy',34);
INSERT INTO Category(category_name,book_id) VALUES ('Historical Fiction',34);
INSERT INTO Category(category_name,book_id) VALUES ('Travel',34);
INSERT INTO Category(category_name,book_id) VALUES ('Biography',35);
INSERT INTO Category(category_name,book_id) VALUES ('Horror',36);
INSERT INTO Category(category_name,book_id) VALUES ('Romance',36);
INSERT INTO Category(category_name,book_id) VALUES ('Crime',36);
INSERT INTO Category(category_name,book_id) VALUES ('Science Fiction',37);
INSERT INTO Category(category_name,book_id) VALUES ('Dystopian',38);
INSERT INTO Category(category_name,book_id) VALUES ('Self-help',38);
INSERT INTO Category(category_name,book_id) VALUES ('Romance',38);
INSERT INTO Category(category_name,book_id) VALUES ('Romance',39);
INSERT INTO Category(category_name,book_id) VALUES ('Travel',39);
INSERT INTO Category(category_name,book_id) VALUES ('Dystopian',39);
INSERT INTO Category(category_name,book_id) VALUES ('Self-help',40);
INSERT INTO Category(category_name,book_id) VALUES ('Romance',40);
INSERT INTO Category(category_name,book_id) VALUES ('Historical Fiction',40);
INSERT INTO Category(category_name,book_id) VALUES ('Poetry',40);
INSERT INTO Category(category_name,book_id) VALUES ('Comedy',41);
INSERT INTO Category(category_name,book_id) VALUES ('Dystopian',42);
INSERT INTO Category(category_name,book_id) VALUES ('Science Fiction',42);
INSERT INTO Category(category_name,book_id) VALUES ('Children''s',43);
INSERT INTO Category(category_name,book_id) VALUES ('Comedy',43);
INSERT INTO Category(category_name,book_id) VALUES ('Dystopian',43);
INSERT INTO Category(category_name,book_id) VALUES ('Classics',43);
INSERT INTO Category(category_name,book_id) VALUES ('Mystery',44);
INSERT INTO Category(category_name,book_id) VALUES ('Self-help',44);
INSERT INTO Category(category_name,book_id) VALUES ('Science Fiction',45);
INSERT INTO Category(category_name,book_id) VALUES ('Dystopian',45);
INSERT INTO Category(category_name,book_id) VALUES ('Philosophy',45);
INSERT INTO Category(category_name,book_id) VALUES ('Romance',45);
INSERT INTO Category(category_name,book_id) VALUES ('Adventure',45);
INSERT INTO Category(category_name,book_id) VALUES ('Science Fiction',46);
INSERT INTO Category(category_name,book_id) VALUES ('Short Stories',46);
INSERT INTO Category(category_name,book_id) VALUES ('Classics',46);
INSERT INTO Category(category_name,book_id) VALUES ('Science Fiction',47);
INSERT INTO Category(category_name,book_id) VALUES ('Children''s',47);
INSERT INTO Category(category_name,book_id) VALUES ('Short Stories',47);
INSERT INTO Category(category_name,book_id) VALUES ('Self-help',48);
INSERT INTO Category(category_name,book_id) VALUES ('Short Stories',48);
INSERT INTO Category(category_name,book_id) VALUES ('Children''s',48);
INSERT INTO Category(category_name,book_id) VALUES ('Classics',48);
INSERT INTO Category(category_name,book_id) VALUES ('Adventure',49);
INSERT INTO Category(category_name,book_id) VALUES ('Mystery',49);
INSERT INTO Category(category_name,book_id) VALUES ('Historical Fiction',50);
INSERT INTO Category(category_name,book_id) VALUES ('Adventure',50);
INSERT INTO Category(category_name,book_id) VALUES ('Romance',50);
INSERT INTO Category(category_name,book_id) VALUES ('Horror',50);
INSERT INTO Category(category_name,book_id) VALUES ('Travel',50);
INSERT INTO Category(category_name,book_id) VALUES ('Horror',51);
INSERT INTO Category(category_name,book_id) VALUES ('Historical Fiction',52);
INSERT INTO Category(category_name,book_id) VALUES ('Children''s',53);
INSERT INTO Category(category_name,book_id) VALUES ('Poetry',53);
INSERT INTO Category(category_name,book_id) VALUES ('Historical Fiction',53);
INSERT INTO Category(category_name,book_id) VALUES ('Travel',53);
INSERT INTO Category(category_name,book_id) VALUES ('Poetry',54);
INSERT INTO Category(category_name,book_id) VALUES ('Thriller',54);
INSERT INTO Category(category_name,book_id) VALUES ('Adventure',54);
INSERT INTO Category(category_name,book_id) VALUES ('Dystopian',55);
INSERT INTO Category(category_name,book_id) VALUES ('Horror',55);
INSERT INTO Category(category_name,book_id) VALUES ('Classics',55);
INSERT INTO Category(category_name,book_id) VALUES ('Crime',55);
INSERT INTO Category(category_name,book_id) VALUES ('Philosophy',56);
INSERT INTO Category(category_name,book_id) VALUES ('Biography',56);
INSERT INTO Category(category_name,book_id) VALUES ('Mystery',56);
INSERT INTO Category(category_name,book_id) VALUES ('Young Adult',56);
INSERT INTO Category(category_name,book_id) VALUES ('Historical Fiction',56);
INSERT INTO Category(category_name,book_id) VALUES ('Children''s',57);
INSERT INTO Category(category_name,book_id) VALUES ('Science Fiction',57);
INSERT INTO Category(category_name,book_id) VALUES ('Romance',57);
INSERT INTO Category(category_name,book_id) VALUES ('Classics',57);
INSERT INTO Category(category_name,book_id) VALUES ('Biography',58);
INSERT INTO Category(category_name,book_id) VALUES ('Young Adult',59);
INSERT INTO Category(category_name,book_id) VALUES ('Adventure',59);
INSERT INTO Category(category_name,book_id) VALUES ('Comedy',59);
INSERT INTO Category(category_name,book_id) VALUES ('Travel',60);
INSERT INTO Category(category_name,book_id) VALUES ('Comedy',60);
INSERT INTO Category(category_name,book_id) VALUES ('Short Stories',60);
INSERT INTO Category(category_name,book_id) VALUES ('Children''s',60);
INSERT INTO Category(category_name,book_id) VALUES ('Self-help',61);
INSERT INTO Category(category_name,book_id) VALUES ('Thriller',62);
INSERT INTO Category(category_name,book_id) VALUES ('Travel',62);
INSERT INTO Category(category_name,book_id) VALUES ('Science Fiction',63);
INSERT INTO Category(category_name,book_id) VALUES ('Fantasy',63);
INSERT INTO Category(category_name,book_id) VALUES ('Poetry',63);
INSERT INTO Category(category_name,book_id) VALUES ('Horror',64);
INSERT INTO Category(category_name,book_id) VALUES ('Adventure',64);
INSERT INTO Category(category_name,book_id) VALUES ('Comedy',64);
INSERT INTO Category(category_name,book_id) VALUES ('Dystopian',64);
INSERT INTO Category(category_name,book_id) VALUES ('Science Fiction',64);
INSERT INTO Category(category_name,book_id) VALUES ('Children''s',65);
INSERT INTO Category(category_name,book_id) VALUES ('Poetry',65);
INSERT INTO Category(category_name,book_id) VALUES ('Thriller',65);
INSERT INTO Category(category_name,book_id) VALUES ('Young Adult',65);
INSERT INTO Category(category_name,book_id) VALUES ('Comedy',65);
INSERT INTO Category(category_name,book_id) VALUES ('Short Stories',66);
INSERT INTO Category(category_name,book_id) VALUES ('Young Adult',66);
INSERT INTO Category(category_name,book_id) VALUES ('Romance',66);
INSERT INTO Category(category_name,book_id) VALUES ('Thriller',67);
INSERT INTO Category(category_name,book_id) VALUES ('Fantasy',67);
INSERT INTO Category(category_name,book_id) VALUES ('Travel',67);
INSERT INTO Category(category_name,book_id) VALUES ('Science Fiction',67);
INSERT INTO Category(category_name,book_id) VALUES ('Children''s',67);
INSERT INTO Category(category_name,book_id) VALUES ('Young Adult',68);
INSERT INTO Category(category_name,book_id) VALUES ('Fantasy',68);
INSERT INTO Category(category_name,book_id) VALUES ('Historical Fiction',69);
INSERT INTO Category(category_name,book_id) VALUES ('Thriller',69);
INSERT INTO Category(category_name,book_id) VALUES ('Comedy',70);
INSERT INTO Category(category_name,book_id) VALUES ('Self-help',71);
INSERT INTO Category(category_name,book_id) VALUES ('Classics',71);
INSERT INTO Category(category_name,book_id) VALUES ('Crime',71);
INSERT INTO Category(category_name,book_id) VALUES ('Young Adult',71);
INSERT INTO Category(category_name,book_id) VALUES ('Poetry',72);
INSERT INTO Category(category_name,book_id) VALUES ('Children''s',72);
INSERT INTO Category(category_name,book_id) VALUES ('Travel',72);
INSERT INTO Category(category_name,book_id) VALUES ('Comedy',72);
INSERT INTO Category(category_name,book_id) VALUES ('Historical Fiction',73);
INSERT INTO Category(category_name,book_id) VALUES ('Self-help',73);
INSERT INTO Category(category_name,book_id) VALUES ('Romance',73);
INSERT INTO Category(category_name,book_id) VALUES ('Horror',74);
INSERT INTO Category(category_name,book_id) VALUES ('Historical Fiction',74);
INSERT INTO Category(category_name,book_id) VALUES ('Philosophy',74);
INSERT INTO Category(category_name,book_id) VALUES ('Science Fiction',74);
INSERT INTO Category(category_name,book_id) VALUES ('Poetry',75);
INSERT INTO Category(category_name,book_id) VALUES ('Short Stories',75);
INSERT INTO Category(category_name,book_id) VALUES ('Adventure',75);
INSERT INTO Category(category_name,book_id) VALUES ('Fantasy',76);
INSERT INTO Category(category_name,book_id) VALUES ('Self-help',77);
INSERT INTO Category(category_name,book_id) VALUES ('Poetry',77);
INSERT INTO Category(category_name,book_id) VALUES ('Short Stories',77);
INSERT INTO Category(category_name,book_id) VALUES ('Classics',78);
INSERT INTO Category(category_name,book_id) VALUES ('Self-help',78);
INSERT INTO Category(category_name,book_id) VALUES ('Romance',78);
INSERT INTO Category(category_name,book_id) VALUES ('Children''s',79);
INSERT INTO Category(category_name,book_id) VALUES ('Biography',79);
INSERT INTO Category(category_name,book_id) VALUES ('Poetry',79);
INSERT INTO Category(category_name,book_id) VALUES ('Thriller',79);
INSERT INTO Category(category_name,book_id) VALUES ('Adventure',80);
INSERT INTO Category(category_name,book_id) VALUES ('Short Stories',80);
INSERT INTO Category(category_name,book_id) VALUES ('Comedy',80);
INSERT INTO Category(category_name,book_id) VALUES ('Fantasy',80);
INSERT INTO Category(category_name,book_id) VALUES ('Romance',81);
INSERT INTO Category(category_name,book_id) VALUES ('Classics',81);
INSERT INTO Category(category_name,book_id) VALUES ('Adventure',82);
INSERT INTO Category(category_name,book_id) VALUES ('Children''s',83);
INSERT INTO Category(category_name,book_id) VALUES ('Self-help',84);
INSERT INTO Category(category_name,book_id) VALUES ('Adventure',85);
INSERT INTO Category(category_name,book_id) VALUES ('Poetry',85);
INSERT INTO Category(category_name,book_id) VALUES ('Philosophy',86);
INSERT INTO Category(category_name,book_id) VALUES ('Self-help',86);
INSERT INTO Category(category_name,book_id) VALUES ('Historical Fiction',86);
INSERT INTO Category(category_name,book_id) VALUES ('Crime',86);
INSERT INTO Category(category_name,book_id) VALUES ('Self-help',87);
INSERT INTO Category(category_name,book_id) VALUES ('Children''s',87);
INSERT INTO Category(category_name,book_id) VALUES ('Comedy',87);
INSERT INTO Category(category_name,book_id) VALUES ('Philosophy',87);
INSERT INTO Category(category_name,book_id) VALUES ('Travel',87);
INSERT INTO Category(category_name,book_id) VALUES ('Thriller',88);
INSERT INTO Category(category_name,book_id) VALUES ('Horror',88);
INSERT INTO Category(category_name,book_id) VALUES ('Philosophy',88);
INSERT INTO Category(category_name,book_id) VALUES ('Mystery',88);
INSERT INTO Category(category_name,book_id) VALUES ('Travel',88);
INSERT INTO Category(category_name,book_id) VALUES ('Historical Fiction',89);
INSERT INTO Category(category_name,book_id) VALUES ('Thriller',90);
INSERT INTO Category(category_name,book_id) VALUES ('Historical Fiction',90);
INSERT INTO Category(category_name,book_id) VALUES ('Classics',90);
INSERT INTO Category(category_name,book_id) VALUES ('Mystery',90);
INSERT INTO Category(category_name,book_id) VALUES ('Historical Fiction',91);
INSERT INTO Category(category_name,book_id) VALUES ('Fantasy',91);
INSERT INTO Category(category_name,book_id) VALUES ('Adventure',92);
INSERT INTO Category(category_name,book_id) VALUES ('Historical Fiction',92);
INSERT INTO Category(category_name,book_id) VALUES ('Philosophy',92);
INSERT INTO Category(category_name,book_id) VALUES ('Crime',92);
INSERT INTO Category(category_name,book_id) VALUES ('Crime',93);
INSERT INTO Category(category_name,book_id) VALUES ('Children''s',94);
INSERT INTO Category(category_name,book_id) VALUES ('Horror',94);
INSERT INTO Category(category_name,book_id) VALUES ('Philosophy',94);
INSERT INTO Category(category_name,book_id) VALUES ('Young Adult',94);
INSERT INTO Category(category_name,book_id) VALUES ('Mystery',95);
INSERT INTO Category(category_name,book_id) VALUES ('Short Stories',96);
INSERT INTO Category(category_name,book_id) VALUES ('Travel',96);
INSERT INTO Category(category_name,book_id) VALUES ('Thriller',96);
INSERT INTO Category(category_name,book_id) VALUES ('Science Fiction',96);
INSERT INTO Category(category_name,book_id) VALUES ('Horror',97);
INSERT INTO Category(category_name,book_id) VALUES ('Mystery',98);
INSERT INTO Category(category_name,book_id) VALUES ('Travel',98);
INSERT INTO Category(category_name,book_id) VALUES ('Adventure',98);
INSERT INTO Category(category_name,book_id) VALUES ('Romance',98);
INSERT INTO Category(category_name,book_id) VALUES ('Poetry',99);
INSERT INTO Category(category_name,book_id) VALUES ('Travel',99);
INSERT INTO Category(category_name,book_id) VALUES ('Mystery',99);
INSERT INTO Category(category_name,book_id) VALUES ('Adventure',99);
INSERT INTO Category(category_name,book_id) VALUES ('Fantasy',99);
INSERT INTO Category(category_name,book_id) VALUES ('Fantasy',100);
INSERT INTO Category(category_name,book_id) VALUES ('Short Stories',100);
INSERT INTO Category(category_name,book_id) VALUES ('Poetry',100);
INSERT INTO Category(category_name,book_id) VALUES ('Young Adult',100);
