INSERT INTO Keyword(keyword_name,book_id) VALUES ('Relationships',1);
INSERT INTO Keyword(keyword_name,book_id) VALUES ('Thriller',1);
INSERT INTO Keyword(keyword_name,book_id) VALUES ('Historical',1);
INSERT INTO Keyword(keyword_name,book_id) VALUES ('Friendship',1);
INSERT INTO Keyword(keyword_name,book_id) VALUES ('Coming of age',2);
INSERT INTO Keyword(keyword_name,book_id) VALUES ('Nature',2);
INSERT INTO Keyword(keyword_name,book_id) VALUES ('Nature',3);
INSERT INTO Keyword(keyword_name,book_id) VALUES ('Dystopian',3);
INSERT INTO Keyword(keyword_name,book_id) VALUES ('Suspense',3);
INSERT INTO Keyword(keyword_name,book_id) VALUES ('Self-discovery',3);
INSERT INTO Keyword(keyword_name,book_id) VALUES ('Mystery',4);
INSERT INTO Keyword(keyword_name,book_id) VALUES ('Adventure',4);
INSERT INTO Keyword(keyword_name,book_id) VALUES ('Magic',4);
INSERT INTO Keyword(keyword_name,book_id) VALUES ('Coming of age',4);
INSERT INTO Keyword(keyword_name,book_id) VALUES ('Fantasy',5);
INSERT INTO Keyword(keyword_name,book_id) VALUES ('Thriller',5);
INSERT INTO Keyword(keyword_name,book_id) VALUES ('Friendship',5);
INSERT INTO Keyword(keyword_name,book_id) VALUES ('Transformation',5);
INSERT INTO Keyword(keyword_name,book_id) VALUES ('Dystopian',6);
INSERT INTO Keyword(keyword_name,book_id) VALUES ('Friendship',7);
INSERT INTO Keyword(keyword_name,book_id) VALUES ('Magic',7);
INSERT INTO Keyword(keyword_name,book_id) VALUES ('Self-discovery',7);
INSERT INTO Keyword(keyword_name,book_id) VALUES ('Time travel',7);
INSERT INTO Keyword(keyword_name,book_id) VALUES ('War',8);
INSERT INTO Keyword(keyword_name,book_id) VALUES ('Magic',8);
INSERT INTO Keyword(keyword_name,book_id) VALUES ('Friendship',9);
INSERT INTO Keyword(keyword_name,book_id) VALUES ('Love',9);
INSERT INTO Keyword(keyword_name,book_id) VALUES ('Transformation',9);
INSERT INTO Keyword(keyword_name,book_id) VALUES ('Time travel',9);
INSERT INTO Keyword(keyword_name,book_id) VALUES ('Magic',10);
INSERT INTO Keyword(keyword_name,book_id) VALUES ('Transformation',10);
INSERT INTO Keyword(keyword_name,book_id) VALUES ('Time travel',10);
INSERT INTO Keyword(keyword_name,book_id) VALUES ('Nature',10);
INSERT INTO Keyword(keyword_name,book_id) VALUES ('Dystopian',11);
INSERT INTO Keyword(keyword_name,book_id) VALUES ('Nature',11);
INSERT INTO Keyword(keyword_name,book_id) VALUES ('Love',12);
INSERT INTO Keyword(keyword_name,book_id) VALUES ('Time travel',12);
INSERT INTO Keyword(keyword_name,book_id) VALUES ('Love',13);
INSERT INTO Keyword(keyword_name,book_id) VALUES ('Historical',13);
INSERT INTO Keyword(keyword_name,book_id) VALUES ('Friendship',13);
INSERT INTO Keyword(keyword_name,book_id) VALUES ('Coming of age',13);
INSERT INTO Keyword(keyword_name,book_id) VALUES ('Science Fiction',14);
INSERT INTO Keyword(keyword_name,book_id) VALUES ('Magic',14);
INSERT INTO Keyword(keyword_name,book_id) VALUES ('Relationships',14);
INSERT INTO Keyword(keyword_name,book_id) VALUES ('Dystopian',15);
INSERT INTO Keyword(keyword_name,book_id) VALUES ('Self-discovery',15);
INSERT INTO Keyword(keyword_name,book_id) VALUES ('Romance',15);
INSERT INTO Keyword(keyword_name,book_id) VALUES ('Suspense',15);
INSERT INTO Keyword(keyword_name,book_id) VALUES ('Time travel',16);
INSERT INTO Keyword(keyword_name,book_id) VALUES ('Science Fiction',16);
INSERT INTO Keyword(keyword_name,book_id) VALUES ('Nature',16);
INSERT INTO Keyword(keyword_name,book_id) VALUES ('Mystery',17);
INSERT INTO Keyword(keyword_name,book_id) VALUES ('Magic',17);
INSERT INTO Keyword(keyword_name,book_id) VALUES ('Relationships',17);
INSERT INTO Keyword(keyword_name,book_id) VALUES ('Suspense',17);
INSERT INTO Keyword(keyword_name,book_id) VALUES ('Dystopian',17);
INSERT INTO Keyword(keyword_name,book_id) VALUES ('Transformation',18);
INSERT INTO Keyword(keyword_name,book_id) VALUES ('Romance',18);
INSERT INTO Keyword(keyword_name,book_id) VALUES ('Dystopian',19);
INSERT INTO Keyword(keyword_name,book_id) VALUES ('Fantasy',19);
INSERT INTO Keyword(keyword_name,book_id) VALUES ('Fantasy',20);
INSERT INTO Keyword(keyword_name,book_id) VALUES ('Self-discovery',20);
INSERT INTO Keyword(keyword_name,book_id) VALUES ('Relationships',20);
INSERT INTO Keyword(keyword_name,book_id) VALUES ('Romance',20);
INSERT INTO Keyword(keyword_name,book_id) VALUES ('Coming of age',21);
INSERT INTO Keyword(keyword_name,book_id) VALUES ('Science Fiction',21);
INSERT INTO Keyword(keyword_name,book_id) VALUES ('Love',21);
INSERT INTO Keyword(keyword_name,book_id) VALUES ('War',22);
INSERT INTO Keyword(keyword_name,book_id) VALUES ('Friendship',23);
INSERT INTO Keyword(keyword_name,book_id) VALUES ('Relationships',24);
INSERT INTO Keyword(keyword_name,book_id) VALUES ('Young Adult',24);
INSERT INTO Keyword(keyword_name,book_id) VALUES ('Historical',25);
INSERT INTO Keyword(keyword_name,book_id) VALUES ('Nature',25);
INSERT INTO Keyword(keyword_name,book_id) VALUES ('Magic',26);
INSERT INTO Keyword(keyword_name,book_id) VALUES ('Suspense',27);
INSERT INTO Keyword(keyword_name,book_id) VALUES ('Nature',27);
INSERT INTO Keyword(keyword_name,book_id) VALUES ('Self-discovery',27);
INSERT INTO Keyword(keyword_name,book_id) VALUES ('Young Adult',28);
INSERT INTO Keyword(keyword_name,book_id) VALUES ('Love',29);
INSERT INTO Keyword(keyword_name,book_id) VALUES ('Coming of age',30);
INSERT INTO Keyword(keyword_name,book_id) VALUES ('Friendship',30);
INSERT INTO Keyword(keyword_name,book_id) VALUES ('Relationships',30);
INSERT INTO Keyword(keyword_name,book_id) VALUES ('Nature',30);
INSERT INTO Keyword(keyword_name,book_id) VALUES ('Romance',30);
INSERT INTO Keyword(keyword_name,book_id) VALUES ('Historical',31);
INSERT INTO Keyword(keyword_name,book_id) VALUES ('Love',31);
INSERT INTO Keyword(keyword_name,book_id) VALUES ('Relationships',31);
INSERT INTO Keyword(keyword_name,book_id) VALUES ('War',32);
INSERT INTO Keyword(keyword_name,book_id) VALUES ('Time travel',32);
INSERT INTO Keyword(keyword_name,book_id) VALUES ('Relationships',32);
INSERT INTO Keyword(keyword_name,book_id) VALUES ('Magic',32);
INSERT INTO Keyword(keyword_name,book_id) VALUES ('Magic',33);
INSERT INTO Keyword(keyword_name,book_id) VALUES ('Coming of age',33);
INSERT INTO Keyword(keyword_name,book_id) VALUES ('Nature',33);
INSERT INTO Keyword(keyword_name,book_id) VALUES ('Friendship',33);
INSERT INTO Keyword(keyword_name,book_id) VALUES ('Coming of age',34);
INSERT INTO Keyword(keyword_name,book_id) VALUES ('Relationships',35);
INSERT INTO Keyword(keyword_name,book_id) VALUES ('Suspense',36);
INSERT INTO Keyword(keyword_name,book_id) VALUES ('Adventure',36);
INSERT INTO Keyword(keyword_name,book_id) VALUES ('Romance',36);
INSERT INTO Keyword(keyword_name,book_id) VALUES ('Mystery',36);
INSERT INTO Keyword(keyword_name,book_id) VALUES ('Dystopian',36);
INSERT INTO Keyword(keyword_name,book_id) VALUES ('Relationships',37);
INSERT INTO Keyword(keyword_name,book_id) VALUES ('Mystery',38);
INSERT INTO Keyword(keyword_name,book_id) VALUES ('Coming of age',39);
INSERT INTO Keyword(keyword_name,book_id) VALUES ('Magic',39);
INSERT INTO Keyword(keyword_name,book_id) VALUES ('Adventure',40);
INSERT INTO Keyword(keyword_name,book_id) VALUES ('Time travel',40);
INSERT INTO Keyword(keyword_name,book_id) VALUES ('Coming of age',40);
INSERT INTO Keyword(keyword_name,book_id) VALUES ('Historical',40);
INSERT INTO Keyword(keyword_name,book_id) VALUES ('Time travel',41);
INSERT INTO Keyword(keyword_name,book_id) VALUES ('War',41);
INSERT INTO Keyword(keyword_name,book_id) VALUES ('Dystopian',42);
INSERT INTO Keyword(keyword_name,book_id) VALUES ('Historical',42);
INSERT INTO Keyword(keyword_name,book_id) VALUES ('Magic',42);
INSERT INTO Keyword(keyword_name,book_id) VALUES ('Mystery',43);
INSERT INTO Keyword(keyword_name,book_id) VALUES ('Magic',43);
INSERT INTO Keyword(keyword_name,book_id) VALUES ('Adventure',43);
INSERT INTO Keyword(keyword_name,book_id) VALUES ('Historical',44);
INSERT INTO Keyword(keyword_name,book_id) VALUES ('Suspense',44);
INSERT INTO Keyword(keyword_name,book_id) VALUES ('Magic',45);
INSERT INTO Keyword(keyword_name,book_id) VALUES ('Suspense',45);
INSERT INTO Keyword(keyword_name,book_id) VALUES ('Thriller',45);
INSERT INTO Keyword(keyword_name,book_id) VALUES ('Relationships',46);
INSERT INTO Keyword(keyword_name,book_id) VALUES ('Mystery',46);
INSERT INTO Keyword(keyword_name,book_id) VALUES ('Coming of age',47);
INSERT INTO Keyword(keyword_name,book_id) VALUES ('Nature',47);
INSERT INTO Keyword(keyword_name,book_id) VALUES ('Adventure',47);
INSERT INTO Keyword(keyword_name,book_id) VALUES ('Historical',48);
INSERT INTO Keyword(keyword_name,book_id) VALUES ('Coming of age',49);
INSERT INTO Keyword(keyword_name,book_id) VALUES ('Suspense',49);
INSERT INTO Keyword(keyword_name,book_id) VALUES ('Mystery',50);
INSERT INTO Keyword(keyword_name,book_id) VALUES ('Science Fiction',50);
INSERT INTO Keyword(keyword_name,book_id) VALUES ('Dystopian',50);
INSERT INTO Keyword(keyword_name,book_id) VALUES ('Transformation',50);
INSERT INTO Keyword(keyword_name,book_id) VALUES ('Self-discovery',50);
INSERT INTO Keyword(keyword_name,book_id) VALUES ('Coming of age',51);
INSERT INTO Keyword(keyword_name,book_id) VALUES ('Relationships',51);
INSERT INTO Keyword(keyword_name,book_id) VALUES ('Fantasy',51);
INSERT INTO Keyword(keyword_name,book_id) VALUES ('Romance',51);
INSERT INTO Keyword(keyword_name,book_id) VALUES ('Transformation',52);
INSERT INTO Keyword(keyword_name,book_id) VALUES ('Relationships',52);
INSERT INTO Keyword(keyword_name,book_id) VALUES ('Coming of age',52);
INSERT INTO Keyword(keyword_name,book_id) VALUES ('Historical',53);
INSERT INTO Keyword(keyword_name,book_id) VALUES ('Magic',53);
INSERT INTO Keyword(keyword_name,book_id) VALUES ('Time travel',53);
INSERT INTO Keyword(keyword_name,book_id) VALUES ('Thriller',53);
INSERT INTO Keyword(keyword_name,book_id) VALUES ('Dystopian',54);
INSERT INTO Keyword(keyword_name,book_id) VALUES ('Time travel',54);
INSERT INTO Keyword(keyword_name,book_id) VALUES ('Friendship',54);
INSERT INTO Keyword(keyword_name,book_id) VALUES ('Dystopian',55);
INSERT INTO Keyword(keyword_name,book_id) VALUES ('Historical',55);
INSERT INTO Keyword(keyword_name,book_id) VALUES ('Magic',55);
INSERT INTO Keyword(keyword_name,book_id) VALUES ('Romance',55);
INSERT INTO Keyword(keyword_name,book_id) VALUES ('Relationships',56);
INSERT INTO Keyword(keyword_name,book_id) VALUES ('Romance',57);
INSERT INTO Keyword(keyword_name,book_id) VALUES ('Friendship',57);
INSERT INTO Keyword(keyword_name,book_id) VALUES ('Suspense',57);
INSERT INTO Keyword(keyword_name,book_id) VALUES ('Science Fiction',57);
INSERT INTO Keyword(keyword_name,book_id) VALUES ('Dystopian',58);
INSERT INTO Keyword(keyword_name,book_id) VALUES ('Transformation',58);
INSERT INTO Keyword(keyword_name,book_id) VALUES ('Relationships',58);
INSERT INTO Keyword(keyword_name,book_id) VALUES ('Time travel',59);
INSERT INTO Keyword(keyword_name,book_id) VALUES ('Dystopian',59);
INSERT INTO Keyword(keyword_name,book_id) VALUES ('Transformation',60);
INSERT INTO Keyword(keyword_name,book_id) VALUES ('Romance',60);
INSERT INTO Keyword(keyword_name,book_id) VALUES ('Dystopian',60);
INSERT INTO Keyword(keyword_name,book_id) VALUES ('Love',61);
INSERT INTO Keyword(keyword_name,book_id) VALUES ('Self-discovery',61);
INSERT INTO Keyword(keyword_name,book_id) VALUES ('Dystopian',61);
INSERT INTO Keyword(keyword_name,book_id) VALUES ('Thriller',61);
INSERT INTO Keyword(keyword_name,book_id) VALUES ('Romance',61);
INSERT INTO Keyword(keyword_name,book_id) VALUES ('Friendship',62);
INSERT INTO Keyword(keyword_name,book_id) VALUES ('Time travel',62);
INSERT INTO Keyword(keyword_name,book_id) VALUES ('Fantasy',63);
INSERT INTO Keyword(keyword_name,book_id) VALUES ('Nature',63);
INSERT INTO Keyword(keyword_name,book_id) VALUES ('Romance',63);
INSERT INTO Keyword(keyword_name,book_id) VALUES ('Self-discovery',64);
INSERT INTO Keyword(keyword_name,book_id) VALUES ('Nature',64);
INSERT INTO Keyword(keyword_name,book_id) VALUES ('Magic',65);
INSERT INTO Keyword(keyword_name,book_id) VALUES ('Magic',66);
INSERT INTO Keyword(keyword_name,book_id) VALUES ('Love',66);
INSERT INTO Keyword(keyword_name,book_id) VALUES ('Friendship',66);
INSERT INTO Keyword(keyword_name,book_id) VALUES ('Transformation',66);
INSERT INTO Keyword(keyword_name,book_id) VALUES ('Love',67);
INSERT INTO Keyword(keyword_name,book_id) VALUES ('Thriller',67);
INSERT INTO Keyword(keyword_name,book_id) VALUES ('Dystopian',67);
INSERT INTO Keyword(keyword_name,book_id) VALUES ('Self-discovery',68);
INSERT INTO Keyword(keyword_name,book_id) VALUES ('Transformation',68);
INSERT INTO Keyword(keyword_name,book_id) VALUES ('Dystopian',68);
INSERT INTO Keyword(keyword_name,book_id) VALUES ('Transformation',69);
INSERT INTO Keyword(keyword_name,book_id) VALUES ('Thriller',69);
INSERT INTO Keyword(keyword_name,book_id) VALUES ('Romance',69);
INSERT INTO Keyword(keyword_name,book_id) VALUES ('Young Adult',69);
INSERT INTO Keyword(keyword_name,book_id) VALUES ('Fantasy',70);
INSERT INTO Keyword(keyword_name,book_id) VALUES ('Science Fiction',70);
INSERT INTO Keyword(keyword_name,book_id) VALUES ('Thriller',70);
INSERT INTO Keyword(keyword_name,book_id) VALUES ('Dystopian',70);
INSERT INTO Keyword(keyword_name,book_id) VALUES ('War',71);
INSERT INTO Keyword(keyword_name,book_id) VALUES ('Romance',71);
INSERT INTO Keyword(keyword_name,book_id) VALUES ('Nature',71);
INSERT INTO Keyword(keyword_name,book_id) VALUES ('Young Adult',72);
INSERT INTO Keyword(keyword_name,book_id) VALUES ('Nature',73);
INSERT INTO Keyword(keyword_name,book_id) VALUES ('Transformation',73);
INSERT INTO Keyword(keyword_name,book_id) VALUES ('Time travel',74);
INSERT INTO Keyword(keyword_name,book_id) VALUES ('Mystery',74);
INSERT INTO Keyword(keyword_name,book_id) VALUES ('Dystopian',74);
INSERT INTO Keyword(keyword_name,book_id) VALUES ('Young Adult',74);
INSERT INTO Keyword(keyword_name,book_id) VALUES ('Coming of age',75);
INSERT INTO Keyword(keyword_name,book_id) VALUES ('Relationships',75);
INSERT INTO Keyword(keyword_name,book_id) VALUES ('Mystery',75);
INSERT INTO Keyword(keyword_name,book_id) VALUES ('Time travel',76);
INSERT INTO Keyword(keyword_name,book_id) VALUES ('War',76);
INSERT INTO Keyword(keyword_name,book_id) VALUES ('Romance',76);
INSERT INTO Keyword(keyword_name,book_id) VALUES ('Transformation',77);
INSERT INTO Keyword(keyword_name,book_id) VALUES ('Young Adult',77);
INSERT INTO Keyword(keyword_name,book_id) VALUES ('Fantasy',78);
INSERT INTO Keyword(keyword_name,book_id) VALUES ('Adventure',78);
INSERT INTO Keyword(keyword_name,book_id) VALUES ('Love',79);
INSERT INTO Keyword(keyword_name,book_id) VALUES ('Friendship',79);
INSERT INTO Keyword(keyword_name,book_id) VALUES ('Historical',80);
INSERT INTO Keyword(keyword_name,book_id) VALUES ('Coming of age',81);
INSERT INTO Keyword(keyword_name,book_id) VALUES ('Young Adult',82);
INSERT INTO Keyword(keyword_name,book_id) VALUES ('Mystery',82);
INSERT INTO Keyword(keyword_name,book_id) VALUES ('Nature',83);
INSERT INTO Keyword(keyword_name,book_id) VALUES ('Adventure',83);
INSERT INTO Keyword(keyword_name,book_id) VALUES ('Fantasy',83);
INSERT INTO Keyword(keyword_name,book_id) VALUES ('Adventure',84);
INSERT INTO Keyword(keyword_name,book_id) VALUES ('Dystopian',84);
INSERT INTO Keyword(keyword_name,book_id) VALUES ('Mystery',84);
INSERT INTO Keyword(keyword_name,book_id) VALUES ('Nature',84);
INSERT INTO Keyword(keyword_name,book_id) VALUES ('Thriller',84);
INSERT INTO Keyword(keyword_name,book_id) VALUES ('Transformation',85);
INSERT INTO Keyword(keyword_name,book_id) VALUES ('Magic',85);
INSERT INTO Keyword(keyword_name,book_id) VALUES ('Magic',86);
INSERT INTO Keyword(keyword_name,book_id) VALUES ('Historical',86);
INSERT INTO Keyword(keyword_name,book_id) VALUES ('Young Adult',87);
INSERT INTO Keyword(keyword_name,book_id) VALUES ('Coming of age',88);
INSERT INTO Keyword(keyword_name,book_id) VALUES ('Thriller',88);
INSERT INTO Keyword(keyword_name,book_id) VALUES ('Time travel',88);
INSERT INTO Keyword(keyword_name,book_id) VALUES ('Science Fiction',89);
INSERT INTO Keyword(keyword_name,book_id) VALUES ('Suspense',90);
INSERT INTO Keyword(keyword_name,book_id) VALUES ('Fantasy',90);
INSERT INTO Keyword(keyword_name,book_id) VALUES ('Friendship',91);
INSERT INTO Keyword(keyword_name,book_id) VALUES ('Transformation',92);
INSERT INTO Keyword(keyword_name,book_id) VALUES ('Thriller',92);
INSERT INTO Keyword(keyword_name,book_id) VALUES ('Young Adult',92);
INSERT INTO Keyword(keyword_name,book_id) VALUES ('Dystopian',92);
INSERT INTO Keyword(keyword_name,book_id) VALUES ('Nature',93);
INSERT INTO Keyword(keyword_name,book_id) VALUES ('Young Adult',93);
INSERT INTO Keyword(keyword_name,book_id) VALUES ('Thriller',93);
INSERT INTO Keyword(keyword_name,book_id) VALUES ('Magic',93);
INSERT INTO Keyword(keyword_name,book_id) VALUES ('Romance',94);
INSERT INTO Keyword(keyword_name,book_id) VALUES ('Suspense',94);
INSERT INTO Keyword(keyword_name,book_id) VALUES ('Transformation',94);
INSERT INTO Keyword(keyword_name,book_id) VALUES ('Historical',94);
INSERT INTO Keyword(keyword_name,book_id) VALUES ('Coming of age',94);
INSERT INTO Keyword(keyword_name,book_id) VALUES ('Fantasy',95);
INSERT INTO Keyword(keyword_name,book_id) VALUES ('Transformation',95);
INSERT INTO Keyword(keyword_name,book_id) VALUES ('Relationships',96);
INSERT INTO Keyword(keyword_name,book_id) VALUES ('Nature',96);
INSERT INTO Keyword(keyword_name,book_id) VALUES ('Love',96);
INSERT INTO Keyword(keyword_name,book_id) VALUES ('Thriller',97);
INSERT INTO Keyword(keyword_name,book_id) VALUES ('Magic',97);
INSERT INTO Keyword(keyword_name,book_id) VALUES ('Magic',98);
INSERT INTO Keyword(keyword_name,book_id) VALUES ('Adventure',98);
INSERT INTO Keyword(keyword_name,book_id) VALUES ('Friendship',98);
INSERT INTO Keyword(keyword_name,book_id) VALUES ('Suspense',98);
INSERT INTO Keyword(keyword_name,book_id) VALUES ('Magic',99);
INSERT INTO Keyword(keyword_name,book_id) VALUES ('Love',99);
INSERT INTO Keyword(keyword_name,book_id) VALUES ('Fantasy',99);
INSERT INTO Keyword(keyword_name,book_id) VALUES ('Historical',100);
INSERT INTO Keyword(keyword_name,book_id) VALUES ('Young Adult',100);
INSERT INTO Keyword(keyword_name,book_id) VALUES ('Transformation',100);
